version: '3'
services:
  user-service:
    image: user-service
    build:
      context: ./user-service
    ports:
      - "8081:8081"
  organisation-service:
    image: organisation-service
    build:
      context: ./organisation-service
    ports:
      - "8082:8082"
  gateway-service:
    image: gateway-service
    build:
      context: ./gateway-service
    ports:
      - "8080:8080"
